# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'sione' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for sione
  pod 'Firebase/Core', '~> 5.20.1'
  pod 'Firebase/Auth', '~> 5.20.1'
  pod 'Firebase/Database', '~> 5.20.1'
  pod 'Firebase/Storage', '~> 5.20.1'
  pod 'RNSVG', :path => '../node_modules/react-native-svg'
  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
      'RCTImage',
    ]

  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  target 'sione-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'sioneTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'sione-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for sione-tvOS


end

post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == "React"
        target.remove_from_project
      end
    end
  end
